# Generated by Django 5.2.6 on 2025-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('publish_date', models.DateField()),
                ('genres', models.CharField(choices=[('FIN', 'Fiction'), ('HIS', 'History'), ('SCI', 'Science'), ('FANT', 'Fantasy')], max_length=10)),
                ('price', models.BigIntegerField()),
                ('authors', models.ManyToManyField(related_name='Book', to='book.author')),
            ],
        ),
    ]
